### ISSUE TITLE
 Given an address, describe safety concerns

### ISSUE THREAD

**Issue by banjtheman** [CharlotteJackson/DC_Crash_Bot#108]
# What is the Task

Given an address, describe the safety concerns

## Why do we want to do this

Step 2 of the TSA is:   
Provide a detailed description of the problems observed in the area of investigation (vehicle crashes, speeding, pedestrian safety, bicycle safety, unable to cross the street, hard-to-see cross‐traffic, etc.) For intersection‐related concerns, please include the type of intersection:

## How can I get started?
We can leverage the work from #82 as it uses the same dataset  

https://github.com/CharlotteJackson/DC_Crash_Bot/blob/master/data/analysis_data_dc_crashes_w_details.csv

We can use speed camera data as well to see how much speeding happens in the area.

## Definition of Done

Have a function that can provide a list of safety concerns

**Comment by CharlotteJackson** [comment]
the speed camera data is all aggregated in analysis_data.moving_violations. The original files on Open Data DC are split out by month, so maybe kind of a pain to use for this purpose

**Comment by banjtheman** [comment]
Example output for 4915 Sheriff Rd NE, Washington, DC 20019

```
There have been 16 crashes in the past year.
There have been 57 moving violations in the past year.

Pedestrian Stats:
pedestrian injuries: 0
pedestrian fatalities: 0

Bicycle Stats:
bicycle injuries: 0
bicycle fatalities: 0

Vehicle Stats:
vehicle injuries: 8
vehicle fatalities: 0

Moving violations types:
NO FRONT TAGS : 4
FAIL TO EXHIBIT REGISTRATION : 3
FAIL TO DISPLAY CURRENT INSPECTION STICKER : 7
UNREGISTERED VEHICLE, MORE THAN 30 DAYS : 7
PASSING STOP SIGN WITHOUT COMING TO A FULL STOP : 7
FAIL TO PROPERLY FASTEN TAGS TO VEHICLE : 1
VIOLATION OF RESTRICTION ON LEARNER'S PERMIT : 1
FAIL TO EXHIBIT DRIVER'S LICENSE OR PERMIT : 2
DISTRACTED DRIVING USING CELL PHONE, OTHER DEVICE : 2
FAIL TO KEEP IN LANE : 1
SPEED 11-15 MPH OVER THE SPEED LIMIT : 12
SPEED 16-20 MPH OVER THE SPEED LIMIT : 3
SPEED 21-25 MPH OVER THE SPEED LIMIT : 1
FAIL TO DISPLAY PROOF OF VEHICLE INSURANCE : 2
OWNER OPERATE OR PERMIT OPERATION OF UNINSRD VEH : 2
PERMIT UNAUTHORIZED PERSON TO OPERATE VEHICLE : 1
FAIL TO YIELD RIGHT OF WAY : 1

State Plate types:
VA Plate Count: 22
DC Plate Count: 11
MD Plate Count: 17
IN Plate Count: 1
WV Plate Count: 2
MA Plate Count: 2
NY Plate Count: 2
```
