### ISSUE TITLE
Given an address, determine the average speed of Waze users on the block and how many of them are speeding

### ISSUE THREAD

**Issue by CharlotteJackson** [CharlotteJackson/DC_Crash_Bot#112]
# What is the Task
Given an address, pull the average speed of Waze users on the block and also how many of them are speeding by 10+ and 20+ mpg

## Why do we want to do this
To add to the data-driven traffic safety assessment tool

## How can I get started?
Pull data from analysis_data.avg_waze_speed_by_roadway_block and/or analysis_data.percentiles_waze_speed_by_roadway_block

## Definition of Done
When the average speed of Waze users is integrated into the data driven traffic safety tool

**Comment by banjtheman** [comment]
Example of waze data mean from analysis_data.avg_waze_speed_by_roadway_block using the avg_speed_mph_moving_users
```
Testing using address: 4915 Sheriff Rd NE, Washington, DC 20019

...

Speed limit: 25.0  
Mean speed from Waze 16.64396179915176
```
