### ISSUE TITLE
Get WalkScore for all DC addresses

### ISSUE THREAD

**Issue by CharlotteJackson** [CharlotteJackson/DC_Crash_Bot#48]
# What is the Task
Use the free version of the Walkscore API to pull Walkscore data for every address in the DC Address Points table

## Why do we want to do this
As part of our larger goal to understand traffic safety in DC

## How can I get started?
Get access to the database and Charlotte's Walkscore API key

## Definition of Done
When there's a table in the DB of all addresses and walk scores, and a script that can be run to refresh them at any point

**Comment by banjtheman** [comment]
Says the key can take 2 days to review... but once we have it can use this python package https://pypi.org/project/walkscore-api/
