### ISSUE TITLE
Tweets - Location data

### ISSUE THREAD

**Issue by CharlotteJackson** [CharlotteJackson/DC_Crash_Bot#5]
# What is the Task
1 - Scrape the tweet JSON for anything formatted like an address
2 - Use a Mapbox API endpoint to convert the address to lat/long/geometry

## Why do we want to do this
To incorporate data on crashes that may not get added to the DC Open Data crash dataset

## How can I get started?
Use the sample tweet jsons from AlertDC.io that Banjo added to the repo and Charlotte's Mapbox developer API keys

## Definition of Done
We have investigated a dozen or so sample tweets and confirmed that we can or cannot extract geometry data from them

**Comment by banjtheman** [comment]
Data: https://github.com/CharlotteJackson/DC_Crash_Bot/blob/311_lat_long_%235/data/AlertDCio_google_geo.json
Script: https://github.com/CharlotteJackson/DC_Crash_Bot/blob/311_lat_long_%235/scripts/get_tweet_address.py
