### ISSUE TITLE
Stand up S3 bucket

### ISSUE THREAD

**Issue by CharlotteJackson** [CharlotteJackson/DC_Crash_Bot#7]
# What is the Task
Add users to AWS account and put data in S3 buckets

## Why do we want to do this
because data does not belong in git

## How can I get started?
Charlotte will poke around the AWS console and figure it out

## Definition of Done
when everyone who wants AWS credentials for this project has them, and we have data in there

**Comment by banjtheman** [comment]
Would create a bucket

1. called tweets
2. Have a folder for each user i.e  AlertDCio
3. Place this static json file there for now 
https://raw.githubusercontent.com/CharlotteJackson/DC_Crash_Bot/master/data/AlertDCio_google_geo.json
