### ISSUE TITLE
Given an address, Describe multi‐modal facilities

### ISSUE THREAD

**Issue by banjtheman** [CharlotteJackson/DC_Crash_Bot#85]
# What is the Task
Create function to get multi‐modal facilities given an address

## Why do we want to do this
Step 6 for the TSA is to Describe multi‐modal facilities
Are there sidewalks? Bike facilities or trails? Nearby Metrorail station or Metrobus stop(s)?

## How can I get started?
We have metro data - https://docs.google.com/spreadsheets/d/18OQh78KhlL65JHM2DyQKVEdYUY8zXjHzTfYbdsd-Kes/edit#gid=821041532

We have road calming features - https://docs.google.com/spreadsheets/d/18OQh78KhlL65JHM2DyQKVEdYUY8zXjHzTfYbdsd-Kes/edit#gid=2064723036

Will have to look for trails and any other points of interest

## Definition of Done
A Function given an address returns multi‐modal facilities

**Comment by banjtheman** [comment]
Bike trails: https://opendata.dc.gov/datasets/bike-trails/explore?location=14.465233%2C59.704936%2C0.00&showTable=true

Sidwalks: https://opendata.dc.gov/datasets/sidewalks/explore?location=14.465233%2C59.704936%2C0.00&showTable=true

**Comment by CharlotteJackson** [comment]
Check out source_data.sidewalks and source_data.bike_trails! Are those in the right format to be useful? Also all the columns except the geography are varchars; do you need me to cast anything to numeric or int?

**Comment by banjtheman** [comment]
@CharlotteJackson everything works, thanks!!!

**Comment by banjtheman** [comment]
Example output

```
Address: 607 13th St NW, Washington, DC 20005

Nearby Metro Stations:
Metro Center
Nearby Sidewalk types:
Sidewalk: 82
Crosswalk: 63
Stairs: 12
Hidden Sidewalk: 1
```
