### ISSUE TITLE
Scrape Waze Live Map for incident Data 

### ISSUE THREAD

**Issue by banjtheman** [CharlotteJackson/DC_Crash_Bot#88]
# What is the Task
Create a script that can scrape data from Waze Live map
https://www.waze.com/live-map/

We are interested in the hazard data, road closures, and police activity 

## Why do we want to do this
Waze has very good up-to-date information but doesn't provide a nice API, so we must scrape instead.

## How can I get started?
How can we start this task?

This script is a good starting point, we will want to scrape for the dc area
https://gist.github.com/jossef/1a6c523f99318286bb1f05efd77fcc9e

## Definition of Done
Have script that can collect data from Waze

**Comment by banjtheman** [comment]
Notes:
Theo  has some code to start this

**Comment by CharlotteJackson** [comment]
Done! This is in branch extract_audio_transcriptions. Will merge it in a day or two. It's being scraped and loaded into the database every 20 minutes
