### ISSUE TITLE
Bing as a potential data source? 

### ISSUE THREAD

**Issue by unhott** [CharlotteJackson/DC_Crash_Bot#91]
Hello! I found this and thought maybe it could be a useful data source 
https://docs.microsoft.com/en-us/bingmaps/rest-services/traffic/get-traffic-incidents

**Comment by banjtheman** [comment]
Yea has good info https://docs.microsoft.com/en-us/bingmaps/rest-services/traffic/traffic-incident-data
These are the type of incidents it can find 
```
- 1: Accident
- 2: Congestion
- 3: DisabledVehicle
- 4: MassTransit
- 5: Miscellaneous
- 6: OtherNews
- 7: PlannedEvent
- 8: RoadHazard
- 9: Construction
- 10: Alert
- 11: Weather
```
